### ISSUE TITLE
Allow rendering `markdown::mdast::Node` directly to HTML

### ISSUE THREAD

**Issue by wiktor-k** [wooorm/markdown-rs#156] opened 2024-11-06 15:51 UTC
Hi,

I just found your library and it's working really well! Thanks! :clap: 

I'm using `markdown::to_mdast` to get the AST for some frontmatter parameters and then using `markdown::to_html_with_options` for rendering and if I'm not mistaken this parses the `content` twice.

I think it'd be good to expose converting AST tree to HTML directly so I could parse it just once with `to_mdast` and then convert to HTML from that.

Thanks for your time! :wave:

**Comment by ChristianMurphy** [comment] 2024-11-06 15:56
Welcome @wiktor-k it sounds like you want to do some transformation on content?
If so see #32 

Or if you mostly want AST nodes for another reason see https://github.com/wooorm/markdown-rs/issues/27

**Comment by wooorm** [comment] 2024-11-07 10:27
This indeed seems a duplicate, so closing!

Duplicate of #27

**Closed by wooorm** 2024-11-07 10:27 UTC
