### ISSUE TITLE
Compile mdast to html

### ISSUE THREAD

**Issue by GuillaumeDesforges** [wooorm/markdown-rs#101] opened 2024-01-22 15:41 UTC
I'd like to manipulate the parsed AST before it goes through compilation.

I can get the AST using `to_mdast`, however I can't then compile it to HTML as `to_html::compile` is private in the crate.

**Comment by ChristianMurphy** [comment] 2024-01-22 15:43
Duplicate of https://github.com/wooorm/markdown-rs/issues/32

**Closed by ChristianMurphy** 2024-01-22 15:43 UTC

**Comment by GuillaumeDesforges** [comment] 2024-01-22 15:59
@ChristianMurphy I agree that the end result could be about the same than with a plugin architecture.

That being said, somehow allowing to use `to_html::compile` directly would be a quick win that would not require any complex architecture.

Would you consider making more of the internals public in the crate?

**Comment by wooorm** [comment] 2024-01-22 16:04
`to_html` does not work on ASTs. The functionality you are looking for is not here.

There will not be a mdast -> html transform.
Eventually there will be an mdast -> hast step, and then finally a hast -> html step.
These steps are already privately implemented in https://github.com/wooorm/mdxjs-rs.

Currently, this project is ± at a level of trying to figure out how people want to use it, before committing to particular APIs.

All of these steps are available in the JavaScript world. As this is Rust, the Rust part might affect it.

**Comment by GuillaumeDesforges** [comment] 2024-01-22 16:08
Right, I went through the code too quickly. I understand why it's a duplicate of #32.

Thanks a lot :+1:
