### ISSUE TITLE
API for creating extensions?

### ISSUE THREAD

**Issue by tryoxiss** [wooorm/markdown-rs#93] opened 2023-12-12 22:22 UTC
Hi, I found this crate when looking for a markdown parser but my use case has needs beyond that of commonmark and the provided extensions. If there, or if not could there be, some sort of API to allow creation of custom syntax rules, e.g., callouts, `<ins>`/`<del>` tags, and whatever else people have need for on a more local basis?

**Comment by ChristianMurphy** [comment] 2023-12-12 22:26
Thanks for reaching out @tryoxiss!
This is a duplicate of https://github.com/wooorm/markdown-rs/issues/32
Happy to discuss more there.

**Closed by ChristianMurphy** 2023-12-12 22:26 UTC
